version: '3'

services:
  front-end:
    build:
      context: ./frontend
    ports:
      - "5000"
    expose:
      - 5000

  catalog:
    build:
      context: ./catalog
    ports:
      - "5001"
    expose:
      - 5001

  order:
    build:
      context: ./order
    ports:
      - "5002"
    expose:
      - 5002
